// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "popupPosition": string;
      "enableContext": boolean;
      "provider": string;
      "bedrock.apiKey": string;
      "bedrock.modelId": string;
      "bedrock.region": string;
      "openai.apiKey": string;
      "openai.modelId": string;
      "openai.endpoint": string;
      "targetLanguage": string;
      "wordbookPath": string;
      "debug": boolean;
    };
  }
}
