/**
 * HTML generation for the wordbook static page.
 * Separated from wordbook.ts to keep file sizes manageable.
 */

export function getWordbookCSS(): string {
  return [
    "*{margin:0;padding:0;box-sizing:border-box}",
    'body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",sans-serif;background:#f0f2f5;color:#1a1a2e;line-height:1.6}',
    ".nav{background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:#fff;padding:20px 0;box-shadow:0 2px 10px rgba(102,126,234,.3)}",
    ".container{max-width:1200px;margin:0 auto;padding:0 24px}",
    ".nav .container{display:flex;justify-content:space-between;align-items:center}",
    ".nav h1{font-size:24px;font-weight:700;letter-spacing:-.5px}",
    ".nav .stats{display:flex;gap:24px;font-size:13px;opacity:.95}",
    ".nav .stats span{display:flex;align-items:center;gap:4px}",
    ".nav .stats b{font-size:18px;font-weight:700}",
    ".stats-row{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:12px;margin:20px 0 16px}",
    ".stat-card{background:#fff;border-radius:10px;padding:14px 18px;box-shadow:0 1px 3px rgba(0,0,0,.06);text-align:center}",
    ".stat-card .num{font-size:28px;font-weight:700;color:#667eea}",
    ".stat-card .lbl{font-size:12px;color:#888;margin-top:2px}",
    ".controls{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:0 0 16px}",
    ".controls input[type=text]{flex:1;min-width:220px;padding:10px 16px;border:2px solid #e8e8e8;border-radius:8px;font-size:14px;outline:0;transition:border-color .2s,box-shadow .2s}",
    ".controls input:focus{border-color:#667eea;box-shadow:0 0 0 3px rgba(102,126,234,.12)}",
    ".controls select{padding:10px 32px 10px 14px;border:2px solid #e8e8e8;border-radius:8px;font-size:14px;background:#fff;cursor:pointer;outline:0;transition:border-color .2s}",
    ".controls select:focus{border-color:#667eea}",
    ".cbtn{padding:10px 18px;border:2px solid #667eea;border-radius:8px;background:#fff;color:#667eea;cursor:pointer;font-size:14px;font-weight:600;transition:all .2s;white-space:nowrap}",
    ".cbtn:hover{background:#667eea;color:#fff}",
    ".cbtn.on{background:#667eea;color:#fff}",
    ".export-group{display:flex;gap:6px;margin-left:auto}",
    ".ebtn{padding:8px 14px;border:1px solid #dee2e6;border-radius:8px;background:#fff;color:#555;cursor:pointer;font-size:13px;font-weight:500;transition:all .2s;white-space:nowrap}",
    ".ebtn:hover{border-color:#667eea;color:#667eea;background:#f8f9ff}",
    "table{width:100%;border-collapse:separate;border-spacing:0;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 1px 6px rgba(0,0,0,.06)}",
    "thead{background:#fafbfc}",
    "th{padding:12px 16px;text-align:left;font-size:12px;font-weight:700;color:#666;text-transform:uppercase;letter-spacing:.5px;border-bottom:2px solid #eee}",
    "td{padding:12px 16px;border-bottom:1px solid #f5f5f5;vertical-align:top}",
    "tbody tr{transition:background .15s}",
    "tbody tr:hover{background:#f8f9ff}",
    "tbody tr:last-child td{border-bottom:none}",
    ".star-btn{cursor:pointer;font-size:20px;background:none;border:none;padding:2px 4px;transition:transform .15s;line-height:1}",
    ".star-btn:hover{transform:scale(1.3)}",
    ".word-col{min-width:120px}",
    ".word-col strong{font-size:15px;color:#1a1a2e}",
    ".badge{display:inline-block;padding:2px 8px;border-radius:10px;font-size:10px;font-weight:600;margin-left:6px;text-transform:uppercase;letter-spacing:.3px;vertical-align:middle}",
    ".badge-w{background:#eef0ff;color:#667eea}",
    ".badge-p{background:#e0f7fa;color:#0097a7}",
    ".badge-c{background:#f0f0f0;color:#666;font-size:12px;font-weight:600}",
    '.tcell{font-family:"SF Mono",Monaco,Menlo,Consolas,monospace;font-size:13px;white-space:pre-wrap;word-break:break-word;max-width:450px;line-height:1.7;color:#333;position:relative}',
    ".copy-btn{position:absolute;top:0;right:0;background:#f0f0f0;border:none;border-radius:4px;padding:2px 6px;font-size:11px;cursor:pointer;opacity:0;transition:opacity .2s;color:#666}",
    "td:hover .copy-btn{opacity:1}",
    ".copy-btn:hover{background:#667eea;color:#fff}",
    ".del-btn{padding:4px 10px;border:1px solid #ff6b6b;border-radius:6px;background:#fff;color:#ff6b6b;cursor:pointer;font-size:13px;transition:all .2s}",
    ".del-btn:hover{background:#ff6b6b;color:#fff}",
    ".empty{text-align:center;padding:80px 20px;color:#999}",
    ".empty .em{font-size:56px;margin-bottom:16px}",
    ".empty h3{font-size:18px;color:#666;margin-bottom:8px}",
    ".toast{position:fixed;bottom:24px;right:24px;padding:14px 24px;background:rgba(26,26,46,.9);color:#fff;border-radius:10px;font-size:14px;opacity:0;transform:translateY(12px);transition:all .3s ease;z-index:1000;pointer-events:none;max-width:400px}",
    ".toast.show{opacity:1;transform:translateY(0)}",
    ".info-banner{background:#fff3cd;border:1px solid #ffc107;border-radius:8px;padding:10px 16px;margin-bottom:16px;font-size:13px;color:#856404;display:flex;align-items:center;gap:8px;flex-wrap:wrap}",
    ".info-banner code{background:rgba(0,0,0,.08);padding:2px 6px;border-radius:4px;font-size:12px}",
    "@media(max-width:768px){.nav .container{flex-direction:column;gap:10px;text-align:center}.controls{flex-direction:column}.export-group{margin-left:0;width:100%;justify-content:center}.stats-row{grid-template-columns:repeat(2,1fr)}table{font-size:13px}th,td{padding:8px 10px}}",
  ].join("\n");
}

export function getWordbookJS(): string {
  // Using array join to avoid template literal issues with backticks in JS code
  return [
    'var starOnly=false,curSort="time",sq="";',
    "",
    "function getFiltered(){",
    "  var w=allWords.slice();",
    '  if(sq){var s=sq.toLowerCase();w=w.filter(function(x){return x.word.toLowerCase().indexOf(s)>=0||x.translation.toLowerCase().indexOf(s)>=0})}',
    "  if(starOnly)w=w.filter(function(x){return x.starred});",
    '  if(curSort==="alpha")w.sort(function(a,b){return a.word.localeCompare(b.word)});',
    '  else if(curSort==="count")w.sort(function(a,b){return b.queryCount-a.queryCount});',
    '  else if(curSort==="starred")w.sort(function(a,b){return(b.starred?1:0)-(a.starred?1:0)||new Date(b.updatedAt).getTime()-new Date(a.updatedAt).getTime()});',
    "  else w.sort(function(a,b){return new Date(b.updatedAt).getTime()-new Date(a.updatedAt).getTime()});",
    "  return w;",
    "}",
    "",
    "function updateStats(){",
    "  var st=0,sw=0,ph=0,tq=0;",
    "  for(var j=0;j<allWords.length;j++){if(allWords[j].starred)st++;if(allWords[j].isSingleWord)sw++;else ph++;tq+=allWords[j].queryCount}",
    '  document.getElementById("st").textContent=allWords.length;',
    '  document.getElementById("ss").textContent=st;',
    '  document.getElementById("sn-total").textContent=allWords.length;',
    '  document.getElementById("sn-words").textContent=sw;',
    '  document.getElementById("sn-phrases").textContent=ph;',
    '  document.getElementById("sn-starred").textContent=st;',
    '  document.getElementById("sn-queries").textContent=tq;',
    "}",
    "",
    "function render(){",
    "  var w=getFiltered();",
    '  var el=document.getElementById("wl");',
    "  if(!w.length){",
    '    el.innerHTML=\'<div class="empty"><div class="em">\\u{1F4ED}</div><h3>\'+(sq?"No matching words":"Your wordbook is empty")+\'</h3><p>\'+(sq?"Try a different search":"Start translating in Zotero to build your wordbook!")+\'</p></div>\';',
    "    updateStats();return;",
    "  }",
    "  var h='<table><thead><tr>';",
    '  h+=\'<th style="width:50px">\\u2B50</th><th>Word</th><th>Translation</th><th style="width:70px;text-align:center">Count</th><th style="width:70px;text-align:center">Page</th><th style="width:120px">Time</th><th style="width:60px"></th></tr></thead><tbody>\';',
    "  for(var i=0;i<w.length;i++){",
    "    var x=w[i];var sid=x.id;",
    "    h+='<tr>';",
    '    h+=\'<td><button class="star-btn" data-id="\'+sid+\'" onclick="toggleStar(this.dataset.id)">\'+(x.starred?"\\u2B50":"\\u2606")+\'</button></td>\';',
    '    h+=\'<td class="word-col"><strong>\'+esc(x.word)+\'</strong><span class="badge \'+(x.isSingleWord?"badge-w":"badge-p")+\'">\'+( x.isSingleWord?"Word":"Phrase")+\'</span></td>\';',
    '    h+=\'<td class="tcell" style="position:relative">\'+esc(x.translation)+\'<button class="copy-btn" onclick="copyText(this)" data-text="\'+esc(x.translation).replace(/"/g,\'&quot;\')+\'">Copy</button></td>\';',
    '    h+=\'<td style="text-align:center"><span class="badge badge-c">\'+x.queryCount+\'x</span></td>\';',
    '    h+=\'<td style="text-align:center">\'+(x.pageNumber?"P"+x.pageNumber:"-")+\'</td>\';',
    '    h+=\'<td style="color:#999;font-size:12px">\'+fd(x.updatedAt)+\'</td>\';',
    '    h+=\'<td><button class="del-btn" data-id="\'+sid+\'" data-word="\'+esc(x.word).replace(/"/g,\'&quot;\')+\'" onclick="del(this.dataset.id,this.dataset.word)">\\uD83D\\uDDD1\\uFE0F</button></td>\';',
    "    h+='</tr>';",
    "  }",
    "  h+='</tbody></table>';",
    "  el.innerHTML=h;",
    "  updateStats();",
    "}",
    "",
    'function esc(s){var d=document.createElement("div");d.textContent=s;return d.innerHTML}',
    "",
    "function fd(iso){",
    "  var d=new Date(iso),n=new Date(),ms=n-d,m=Math.floor(ms/6e4),h=Math.floor(ms/36e5),dy=Math.floor(ms/864e5);",
    '  if(m<1)return"just now";if(m<60)return m+"m ago";if(h<24)return h+"h ago";if(dy<7)return dy+"d ago";',
    '  return d.toLocaleDateString("zh-CN",{year:"numeric",month:"short",day:"numeric"});',
    "}",
    "",
    "function toggleStar(id){",
    "  for(var i=0;i<allWords.length;i++){",
    "    if(allWords[i].id===id){allWords[i].starred=!allWords[i].starred;allWords[i].updatedAt=new Date().toISOString();break}",
    "  }",
    "  render();",
    '  toast("Star toggled");',
    "}",
    "",
    "function del(id,word){",
    "  if(!confirm('Delete \"'+word+'\"?'))return;",
    "  allWords=allWords.filter(function(x){return x.id!==id});",
    "  render();",
    '  toast("Deleted from view");',
    "}",
    "",
    "function copyText(btn){",
    '  var text=btn.getAttribute("data-text");',
    "  if(navigator.clipboard){navigator.clipboard.writeText(text).then(function(){toast('Copied!')}).catch(function(){})}",
    "  else{var ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');document.body.removeChild(ta);toast('Copied!')}",
    "}",
    "",
    "function exportCSV(){",
    '  var rows=["Word,Translation,Type,Starred,Count,Page,Created,Updated"];',
    "  var w=getFiltered();",
    "  for(var i=0;i<w.length;i++){",
    "    var x=w[i];",
    '    rows.push([csvE(x.word),csvE(x.translation),x.isSingleWord?"word":"phrase",x.starred?"yes":"no",x.queryCount,x.pageNumber||"",x.createdAt,x.updatedAt].join(","));',
    "  }",
    '  download(rows.join("\\n"),"wordbook.csv","text/csv");',
    '  toast("Exported "+w.length+" words as CSV");',
    "}",
    "",
    "function exportAnki(){",
    "  var w=getFiltered();",
    "  var lines=[];",
    "  for(var i=0;i<w.length;i++){",
    '    lines.push(w[i].word.replace(/\\t/g," ")+"\\t"+w[i].translation.replace(/\\t/g," ").replace(/\\n/g,"<br>"));',
    "  }",
    '  download(lines.join("\\n"),"wordbook-anki.txt","text/tab-separated-values");',
    '  toast("Exported "+w.length+" words for Anki");',
    "}",
    "",
    "function exportJSON(){",
    "  var w=getFiltered();",
    '  download(JSON.stringify(w,null,2),"wordbook.json","application/json");',
    '  toast("Exported "+w.length+" words as JSON");',
    "}",
    "",
    "function csvE(s){",
    '  if(s.indexOf(",")>=0||s.indexOf(\'"\')>=0||s.indexOf("\\n")>=0)return \'"\'+s.replace(/"/g,\'""\')+\'"\';',
    "  return s;",
    "}",
    "",
    "function download(content,filename,mime){",
    '  var blob=new Blob([content],{type:mime+";charset=utf-8"});',
    "  var a=document.createElement('a');",
    "  a.href=URL.createObjectURL(blob);",
    "  a.download=filename;",
    "  document.body.appendChild(a);a.click();document.body.removeChild(a);",
    "  URL.revokeObjectURL(a.href);",
    "}",
    "",
    "function toast(msg){",
    '  var t=document.getElementById("toast");',
    '  t.textContent=msg;t.classList.add("show");',
    '  setTimeout(function(){t.classList.remove("show")},2500);',
    "}",
    "",
    'document.getElementById("qi").addEventListener("input",function(){sq=this.value.trim();render()});',
    'document.getElementById("so").addEventListener("change",function(){curSort=this.value;render()});',
    'document.getElementById("sf").addEventListener("click",function(){starOnly=!starOnly;this.classList.toggle("on",starOnly);render()});',
    "",
    "render();",
  ].join("\n");
}

interface WordStats {
  total: number;
  starred: number;
  singleWords: number;
  phrases: number;
  totalQueries: number;
}

export function buildWordbookHTML(wordsJSON: string, stats: WordStats): string {
  const css = getWordbookCSS();
  const js = getWordbookJS();

  return [
    "<!DOCTYPE html>",
    '<html lang="zh-CN">',
    "<head>",
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    "<title>Vibe Wordbook - " + stats.total + " words</title>",
    "<style>" + css + "</style>",
    "</head>",
    "<body>",
    '<div class="nav"><div class="container">',
    "<h1>&#x1F4D6; Vibe Wordbook</h1>",
    '<div class="stats">',
    '<span>&#x1F4DA; Total: <b id="st">' + stats.total + "</b></span>",
    '<span>&#x2B50; Starred: <b id="ss">' + stats.starred + "</b></span>",
    "</div></div></div>",
    '<div class="container">',
    '<div class="stats-row">',
    '<div class="stat-card"><div class="num" id="sn-total">' + stats.total + '</div><div class="lbl">Total Words</div></div>',
    '<div class="stat-card"><div class="num" id="sn-words">' + stats.singleWords + '</div><div class="lbl">Single Words</div></div>',
    '<div class="stat-card"><div class="num" id="sn-phrases">' + stats.phrases + '</div><div class="lbl">Phrases</div></div>',
    '<div class="stat-card"><div class="num" id="sn-starred">' + stats.starred + '</div><div class="lbl">Starred</div></div>',
    '<div class="stat-card"><div class="num" id="sn-queries">' + stats.totalQueries + '</div><div class="lbl">Total Queries</div></div>',
    "</div>",
    '<div class="controls">',
    '<input type="text" id="qi" placeholder="&#x1F50D; Search words or translations...">',
    '<select id="so">',
    '<option value="time">&#x1F554; Latest</option>',
    '<option value="alpha">&#x1F524; A-Z</option>',
    '<option value="count">&#x1F522; Most Queried</option>',
    '<option value="starred">&#x2B50; Starred First</option>',
    "</select>",
    '<button class="cbtn" id="sf">&#x2B50; Starred Only</button>',
    '<div class="export-group">',
    '<button class="ebtn" onclick="exportCSV()" title="Export as CSV">&#x1F4CB; CSV</button>',
    '<button class="ebtn" onclick="exportAnki()" title="Export for Anki">&#x1F4DD; Anki</button>',
    '<button class="ebtn" onclick="exportJSON()" title="Export as JSON">&#x1F4E6; JSON</button>',
    "</div></div>",
    '<div class="info-banner">',
    "&#x1F4A1; This is a snapshot. Star/delete are in-memory only.",
    " For persistent edits, run: <code>python wordbook/wordbook_server.py</code>",
    "</div>",
    '<div id="wl"></div>',
    "</div>",
    '<div class="toast" id="toast"></div>',
    "<script>",
    "var allWords=" + wordsJSON + ";",
    js,
    "</script>",
    "</body></html>",
  ].join("\n");
}